package youareellclient

// User is a user.
type User struct {
	UserID   string `json:"userid" help:"This is the user ID.  It is auto-generated by the server."`
	Name     string `json:"name" help:"This is the user's full name."`
	GitHubID string `json:"github" help:"This is the user's GitHub handle."`
}

// Message is a message.
type Message struct {
	Sequence  string `json:"sequence" help:"This is the sequence number.  It is auto-generated by the server."`
	Timestamp string `json:"timestamp" help:"This is the time that the message was sent."`
	FromID    string `json:"fromid" help:"This is the GitHub handle of the sender."`
	ToID      string `json:"toid" help:"This is the GitHub handle of the receiver."`
	Message   string `json:"message" help:"This is the message body."`
}
